### ISSUE TITLE
Number size not equal

### ISSUE THREAD

**Issue by echo-five** [h-ibaldo/Raleway_Fixed_Numerals#2]
Hello

Thanks you for your works, this is very helpful.

Now the numbers are aligned, but the size (I means the height) is not equal.
Sometime, when you define the size in px or in em, some numbers are smaller.

This is more visible under 16px and affect each font-weight versions.
![issue](https://cloud.githubusercontent.com/assets/7316937/22502713/66d83470-e86e-11e6-9b17-fe14529f1433.png)
![issue in context](https://cloud.githubusercontent.com/assets/7316937/22502755/a9d317a4-e86e-11e6-9dae-a1d83626e6a0.png)

This is not related to our CSS rules, because we can reproduce it on the test page.
This is may be related to the issue #1...

Thank you for your support ;)

Matt

**Comment by h-ibaldo** [comment]
Hi @echo-five thank you for your contribution.

It seems that you're having problem with the way the font is being rendered on your screen at smaller sizes. This is probably an issue with the original Raleway hinting. Please note that Rawline doesn't change the original size or alignments of Raleway, it only defines Raleway's own Lining Numerals as default, instead of the so criticized Old Style figures.

Now, consider that Raleway is a Display typeface, so you shouldn't be using it for body text or smaller sizes. Here's the official description of this font from Google Fonts website:

"Raleway is an elegant sans-serif typeface family **intended for headings and other large size usage.**"

I suggest you to use Rawline for bigger headings and titles only, and a geometric text font for your body text, like Lato.

**Comment by echo-five** [comment]
Hello,

Thanks for your answer.
We made the choice to change for the Montserrat font ;)

**Comment by h-ibaldo** [comment]
@echo-five Great choice ;)
